# TA Class II

![Imgur](https://i.imgur.com/qjcnN0g.png)
###### Reference : https://www.nature.com/articles/s41586-020-2649-2?fbclid=IwAR2eVEJDARphtHvhwalAE2zS6BM6u14u0XM8EP1o7ITyzSZ2VKmOyXj0XeA

## Quick numpy walkthrough

In [1]:
import numpy as np

### some basics

In [2]:
n = np.zeros(10)
print(type(n))
print('The shape of n is ' + str(n.shape))
n

<class 'numpy.ndarray'>
The shape of n is (10,)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
m = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])     # dimensions
m.shape

(3, 2, 1)

In [4]:
n = np.ones(10)
n

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
n = np.full((7, 7), 7)
n

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [6]:
n = np.linspace(5, 10, 5)
n

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [7]:
n = np.array([10, 10,2])
n

array([10, 10,  2])

In [8]:
n.shape

(3,)

### shape & reshape

![Imgur](https://i.imgur.com/ri1Xr0w.png)
###### Reference : https://fgnt.github.io/python_crashkurs_doc/include/numpy.html

In [9]:
n = np.arange(10,70,2).reshape((10,3))
n

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38],
       [40, 42, 44],
       [46, 48, 50],
       [52, 54, 56],
       [58, 60, 62],
       [64, 66, 68]])

<pre>
n.reshape(-1, 3) means that you want to reshape the array with 3 columns and you don't know what is the number of raws,
assign -1 and numpy will complete the task for you.
</pre>

In [10]:
n.reshape(-1, 3)

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38],
       [40, 42, 44],
       [46, 48, 50],
       [52, 54, 56],
       [58, 60, 62],
       [64, 66, 68]])

In [11]:
n.reshape(3, -1)

array([[10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38, 40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58, 60, 62, 64, 66, 68]])

### index & slicing

In [12]:
print(n)
print('')
print('n[0][1] = ' + str(n[0][1]))
print('n[1][-2] = ' + str(n[1][-2]))

[[10 12 14]
 [16 18 20]
 [22 24 26]
 [28 30 32]
 [34 36 38]
 [40 42 44]
 [46 48 50]
 [52 54 56]
 [58 60 62]
 [64 66 68]]

n[0][1] = 12
n[1][-2] = 18


<pre>what is 「::」 ...?! 「start:end:step」</pre>

In [13]:
print(n)
n[1::3,]

[[10 12 14]
 [16 18 20]
 [22 24 26]
 [28 30 32]
 [34 36 38]
 [40 42 44]
 [46 48 50]
 [52 54 56]
 [58 60 62]
 [64 66 68]]


array([[16, 18, 20],
       [34, 36, 38],
       [52, 54, 56]])

In [14]:
n[::-1,::2]

array([[64, 68],
       [58, 62],
       [52, 56],
       [46, 50],
       [40, 44],
       [34, 38],
       [28, 32],
       [22, 26],
       [16, 20],
       [10, 14]])

In [15]:
sum(n)

array([370, 390, 410])

### mask

In [16]:
print(n > 33)
n[n > 33]

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68])

In [17]:
n_2 = n[n > 33].reshape(3, 6)
n_2

array([[34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68]])

In [18]:
n_2_mask = np.where( n_2 > 45, 1, 1.5) 
n_2_mask

array([[1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
       [1. , 1. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. , 1. ]])

### list + list    vs.   array + array

In [19]:
list_1 = [1,2,3,4,5]
list_2 = [2,4,6,8,10]
print('list_1 + list_2 = ' + str(list_1 + list_2))

array_1 = np.array(list_1)
array_2 = np.array(list_2)
print('array_1 + array_2 = ' + str(array_1 + array_2))

list_1 + list_2 = [1, 2, 3, 4, 5, 2, 4, 6, 8, 10]
array_1 + array_2 = [ 3  6  9 12 15]


In [20]:
print('array_1 + 10 = ' + str(array_1 + 10))
print('array_1 * 10 = ' + str(array_1 * 10))
print('array_1 * array_2 = ' + str(array_1 * array_2))

array_1 + 10 = [11 12 13 14 15]
array_1 * 10 = [10 20 30 40 50]
array_1 * array_2 = [ 2  8 18 32 50]


### Broadcasting

![Imgur](https://i.imgur.com/m28nIzt.png)
###### Reference : https://mathematica.stackexchange.com/questions/99171/how-to-implement-the-general-array-broadcasting-method-from-numpy

In [21]:
a = np.arange(20).reshape(2,5,2)
b_2dim = np.ones(2).reshape(2,1)
print('The shape of a =' + str(a.shape))
print(a)
print('')
print('The shape of b_2dim =' + str(b_2dim.shape))
print(b_2dim)

print('')
b_3dim = b_2dim[:,:,np.newaxis]
print('The shape of b_3dim =' + str(b_3dim.shape))
print(b_3dim)

The shape of a =(2, 5, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]

The shape of b_2dim =(2, 1)
[[1.]
 [1.]]

The shape of b_3dim =(2, 1, 1)
[[[1.]]

 [[1.]]]


In [22]:
ab = a + b_3dim
print('The shape of ab =' + str(ab.shape))
print(ab)

The shape of ab =(2, 5, 2)
[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]
  [ 7.  8.]
  [ 9. 10.]]

 [[11. 12.]
  [13. 14.]
  [15. 16.]
  [17. 18.]
  [19. 20.]]]


In [23]:
np.sum(ab ** 2, dtype=int, axis=-1)

array([[  5,  25,  61, 113, 181],
       [265, 365, 481, 613, 761]])

### vstack   vs.   hstack

In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr10 = np.array([[1,2,3], [4,5,6], [0,0,0]])
arr20 = np.array([[7,8,9], [10,11,12], [1,1,1]])
arrvstack = np.vstack((arr10, arr20))
arrvstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  0,  0],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  1,  1]])

<pre>
These two cannot stack together !

array([[1, 2],
       [4, 5]])
       
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  0,  0],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  1,  1]])

All the input array dimensions for the concatenation axis must match exactly.
</pre>

In [26]:
# How about stacking arrays with different dimentions ?
print('Shape of arr1 = ' + str(arr1.shape))
print('Shape of arr20 = ' + str(arr20.shape))
np.vstack((arr1, arr20))                      # What will happend if we do np.hstack((arr1, arr20)) here? try it!

Shape of arr1 = (3,)
Shape of arr20 = (3, 3)


array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  1,  1]])

In [27]:
arr3 = np.array([[1,2], [3,4], [5,6]])
arr4 = np.array([[7,8], [9,10], [11,12]])
np.hstack((arr3, arr4))

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

### Sort 

In [28]:
x = np.array([2, 1, 4, 3, 50])
x.sort()
print(x)

[ 1  2  3  4 50]


In [29]:
# returns the indices of the sorted elements
x = np.array([2, 1, 4, 3, 50])
i = np.argsort(x)
print(i)

# These indices can then be used to construct the sorted array if desired
x[i]

[1 0 3 2 4]


array([ 1,  2,  3,  4, 50])

### Sorting along rows or columns

In [30]:
rand = np.random.RandomState(87)
X_for_sort = rand.randint(0, 10, (4, 6))
print(X_for_sort)

[[6 6 6 3 0 9]
 [0 8 3 3 8 3]
 [8 7 5 6 2 9]
 [3 8 4 9 4 9]]


In [31]:
# sort each column of X_for_sort
np.sort(X_for_sort, axis=0)

array([[0, 6, 3, 3, 0, 3],
       [3, 7, 4, 3, 2, 9],
       [6, 8, 5, 6, 4, 9],
       [8, 8, 6, 9, 8, 9]])

In [32]:
# sort each row of X_for_sort
np.sort(X_for_sort, axis=1)

array([[0, 3, 6, 6, 6, 9],
       [0, 3, 3, 3, 8, 8],
       [2, 5, 6, 7, 8, 9],
       [3, 4, 4, 8, 9, 9]])

### Partial Sorts

In [33]:
list_for_sort = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(list_for_sort, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [34]:
# partial sort each row
print(X_for_sort)
print('\n')
print(np.partition(X_for_sort, 2, axis=1))

[[6 6 6 3 0 9]
 [0 8 3 3 8 3]
 [8 7 5 6 2 9]
 [3 8 4 9 4 9]]


[[0 3 6 6 6 9]
 [0 3 3 8 8 3]
 [2 5 6 7 8 9]
 [3 4 4 9 8 9]]


### Universal Function ( UFunc )

<pre>
L = [1,2,3,4,5]
L + 5
---------------------------------------------------------------------------
<span style="color: red">TypeError</span>                                Traceback (most recent call last)
<ipython-input-120-6cbace975c8f> in <module>
      1 L = [1,2,3,4,5]
----> 2 L + 5

<span style="color: red">TypeError</span>: can only concatenate list (not "int") to list

so we have to do:
L = [1,2,3,4,5]

for i in range(len(L)):
    L[i] = L[i] + 5

print(L)
>>> [6, 7, 8, 9, 10]


<b>However, loops is significant slower when the number of iterations is large.</b>


<b>This is why we want to use UFuncs.</b>
</pre>

In [35]:
npL = np.array(range(10)).reshape(2,5)
print('The original ndarray is ')
print(str(npL) + '\n')

npL = npL + 5
print('After the operation above, the ndarray become ' )
print(str(npL))

The original ndarray is 
[[0 1 2 3 4]
 [5 6 7 8 9]]

After the operation above, the ndarray become 
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [36]:
# we can also implement more complex function on ndarrays.
# -( 2*x + 3 )^ 2 for all x in npL
-( 2*npL + 3 ) ** 2

array([[-169, -225, -289, -361, -441],
       [-529, -625, -729, -841, -961]], dtype=int32)

### axis

In [37]:
# arr = [[1,2],
#        [3,4],
#        [5,6]]

arr = np.array([[1,2], [3,4], [5,6]])
print('sum(arr, axis = 0) = ' + str(np.sum(arr, axis = 0)))
print('sum(arr, axis = 1) = ' + str(np.sum(arr, axis = 1)))

sum(arr, axis = 0) = [ 9 12]
sum(arr, axis = 1) = [ 3  7 11]


### multiply tuples
<pre>
(3*X^2Y+Y^5Z^3)(2*XYZ-XZ^2)
step 1. Find out all variables and use a tuple as the key and the constant as the value in a dictionary
step 2. Multiply tuples to calculate the result of a item multiplies another item.
step 3. Deal with the repetitions.
</pre>

In [38]:
item_1 = (2,1,0)
item_2 = (0,5,3)
item_3 = (1,1,1)
item_4 = (1,0,2)
dict_1 = {item_1:3, item_2:1}
dict_2 = {item_3:2, item_4:-1}

def multiply(dict_1, dict_2):
    return_dict = {}
    for (i1, c1) in dict_1.items():
        for (i2, c2) in dict_2.items():
            arr1 = np.array(i1)
            arr2 = np.array(i2)
            new_key = tuple(arr1 + arr2)
            new_const = c1 * c2
            if new_key in return_dict:
                return_dict[new_key] += new_const
            else:
                return_dict[new_key] = new_const
    return return_dict

In [39]:
mul_ans = multiply(dict_1, dict_2)
mul_ans

{(3, 2, 1): 6, (3, 1, 2): -3, (1, 6, 4): 2, (1, 5, 5): -1}

# 　